### ISSUE TITLE
Architecture and Software Model

### ISSUE THREAD

**Issue by newojima** [WHUSENG-Y2S1-ISE/.github#3]

**Comment by newojima** [comment]
john-architectureandsoftwaremodel-3

**Comment by lauronjohn** [comment]
<table>
  <tbody>
    <tr>
      <th>Architecture</th>
      <td>Full-stack Client-Server Architecture (Web Application) 
<ul>
<li>Frontend (react.js (html,css,js) tailwind)</li> <ul> <li> Jason and Nelly</li> </ul>
<li> Backend (spring boot + spring mvc restful backend) </li> <ul> 
<li> John and Sif</li> 
<li> Model-view-controller software architecture pattern</li> 
<li> SQL</li>
</ul>
</ul>
Data and Processes
<ol>
<li>Flow Diagrams-process</li>
<li>UML Diagram- classes</li>
<li>Data Entity Diagram</li>
</ol>
Frontend
<ol>
<li>Sitemap Diagram </li>
<li>Design System (branding, font styles, colors used, the atomic elements)</li>
<li>Wireframes</li>
</ol>
</td>
    </tr>
<tr>
<th> Software Model </th>
      <td>
Incremental Development, Agile
      </td>
    </tr>
  </tbody>
</table>
